name: TruffleHog Scan

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: trufflesecurity/truffleHog-actions-scan@master
        with:
          branch: ${{ github.head_ref }}
